generator: BaseBoard.cpp BaseBoard.h Board.cpp Board.h ConcentricBraid.cpp ConcentricBraid.h Defines.h DivideAndConquer.cpp DivideAndConquer.h FourCover.cpp FourCover.h Generator.cpp Generator.h Graph.cpp Graph.h Helpers.cpp Helpers.h Includes.h Input.cpp Input.h Main.cpp NeuralNet.cpp NeuralNet.h Rail.cpp Rail.h Random.cpp Random.h SearchThread.cpp SearchThread.h SearchThreadQueues.cpp SearchThreadQueues.h Structs.cpp Structs.h TakefujiLee.cpp TakefujiLee.h Task.cpp Task.h ThreadSafeQueue.cpp ThreadSafeQueue.h Tile.cpp Tile.h Timer.cpp Timer.h Warnsdorff.cpp Warnsdorff.h
	@ g++ -std=c++11 -O3 -pthread -o generate.exe BaseBoard.cpp Board.cpp ConcentricBraid.cpp DivideAndConquer.cpp FourCover.cpp Generator.cpp Graph.cpp Helpers.cpp Input.cpp Main.cpp NeuralNet.cpp NeuralNet.h Rail.cpp Rail.h Random.cpp Random.h SearchThread.cpp SearchThreadQueues.cpp Structs.cpp TakefujiLee.cpp Task.cpp ThreadSafeQueue.cpp Tile.cpp Timer.cpp  Warnsdorff.cpp 

cleanup:
	rm -f .makefile.* 
